#!/usr/bin/env python
from IRC.Client import IRCClient
import argparse
import io
import tempfile
import time
import random

cmds = [
    "/join {channel}",
    "/migrate {channel}",
    "/msg {user} {message}",
    "/leave {channel}",
    "/leave {channel} {message}",
    "/users {channel}",
    "/nick {newnick}",
]

channels=["#test", "#bots", "#ignore"]
nicks=["bot1", "bot2", "bot3", "bot4", "bot5"]
msgs=["This is a test", "I am a bot", "Are you a bot?"]

class IRCBot(IRCClient):
    def __init__(self, hostname, port):
        self.__botinput = tempfile.TemporaryFile()
        self.__botinput.seek(0)
        self.__lasttime = 0
        super(IRCBot, self).__init__(hostname, port, userinput=self.__botinput)

    def timeStep(self):
        if time.time() - self.__lasttime > 1:
            print time.time() - self.__lasttime
            pos = self.__botinput.tell()
            self.__botinput.seek(0, 2) #go to end of file

            self.__botinput.write(random.choice(cmds).format(
                channel=random.choice(channels),
                user=random.choice(nicks),
                message=random.choice(msgs),
                newnick=random.choice(nicks)) + "\n")
            self.__botinput.seek(pos) #restore position
            self.__lasttime = time.time()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="IRC Client")
    parser.add_argument('--hostname', help="Hostname", default="localhost")
    parser.add_argument('--port', type=int, help="Port", default=50000)

    args = parser.parse_args()

    client = IRCBot(args.hostname, args.port)
    client.run()
